version: "3"
services: 
  jenkins_master:
    image: jenkins/jenkins:lts
    container_name: jenkins_master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/jenkins_home/:/var/jenkins_home
